### ISSUE TITLE
Special QThread with rxqt::run_loop inside

### ISSUE THREAD

**Issue by Stat1cV01D** [tetsurom/rxqt#25]
Hello, tetsurom!
I appreciate the work you've done here as the library brings an insane value to me.

I have a suggestion: shouldn't we have a special QThread that would contain `rxqt::run_loop`? This could be then used for `subscribe_on` method.  
This proved to be useful for me when I tried to move QObjects between QThreads and wanted to process them properly.

I came up with the following code (C++17):
```cpp
#include <QThread>
#include <rxqt.hpp>

class RunLoopThread : public QThread
{
    Q_OBJECT
public:
    using QThread::QThread;

    rxcpp::observe_on_one_worker getObserver() const
    {
        Q_ASSERT(mRunLoop != nullptr);
        return mRunLoop->observe_on_run_loop();
    }

protected:
    void run() override
    {
        rxqt::run_loop rxqt_run_loop;
        mRunLoop = &rxqt_run_loop;

        QThread::run();
    }

private:
    rxqt::run_loop *mRunLoop{nullptr};
};
```

Then I could use it as follows:
```cpp
class Producer: public QObject
{
<...>
};

auto producer = new Producer(this);
auto thread = new RunLoopThread(this);
producer->moveToThread(thread);
thread->start();

rxqt::from_signal(producer, &Producer::dataReceived)
    .observe_on(thread->getObserver())
    .backpressure_buffer(N, [](auto deque) {
        deque.pop_front();
        return deque;
    })
    .subscribe_on(thread->getObserver())
    .subscribe(onNext, onCompleted);
```

Should I propose an actual piece of code? Or you could probably fit the idea into the RxQt yourself.

**Comment by tetsurom** [comment]
Hi @Stat1cV01D 
Thank you for raising this request, and sorry for late.
I have added [new `rxqt::RunLoopThread` class](https://github.com/tetsurom/rxqt/blob/c0d9ba5ece6df745709d1a24469edcefa83854c3/include/rxqt_run_loop_thread.hpp) and [test](https://github.com/tetsurom/rxqt/blob/c0d9ba5ece6df745709d1a24469edcefa83854c3/test/run_loop/run_loop_test.cpp#L104-L124).
(but not documented yet)

> I appreciate the work you've done here as the library brings an insane value to me.

I'm happy to hear of that, thanks!

**Comment by SamTop** [comment]
Hi @tetsurom. Thanks for the great efforts!
I have modified a bit the [test](https://github.com/tetsurom/rxqt/blob/c0d9ba5ece6df745709d1a24469edcefa83854c3/test/run_loop/run_loop_test.cpp#L104-L124) function, to output QThread::currentThreadId() before the observable, and inside subscribe function like this. 
       
`std::cout<< QThread::currentThreadId();

rx::observable<>::timer(milliseconds(5))
  .subscribe_on(workthread.runLoop()->observe_on_run_loop())
  .observe_on(mainthread)
  .subscribe([&](auto) {
      std::cout << QThread::currentThreadId();
      called = true;
  });`

The output ids are the same. Is this behaviour correct?
