### ISSUE TITLE
'QCoreApplication' has not been declared

### ISSUE THREAD

**Issue by kehyoung** [tetsurom/rxqt#26]
Hi tetsurom.
I'm trying to use rxqt for my plain widget UI Qt project.
I wrote the code like below that and I got error like subject.

main.cpp

```
#include "mainwindow.h"
#include <QApplication>
#include <rxqt.hpp>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;

    rxqt::run_loop rxqt_run_loop;
    w.show();

    return a.exec();
}
```

mainwindow.cpp
```
...
#include <rxqt.hpp>

using namespace std::chrono;

namespace Rx {
    using namespace rxcpp;
    using namespace rxcpp::sources;
    using namespace rxcpp::operators;
    using namespace rxcpp::util;
}
...

MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ...
    auto scene = new BlueprintScene(ui->graphicsView);
    ui->graphicsView->setScene(scene);
}
```

blueprintscene.cpp
```
...
#include <rxqt.hpp>
```

I compiled it with only headers in blueprintscene.cpp and got the following error message:

> In file included from ..\rxqt\include/rxqt.hpp:7:0,
> from ..\blueprintscene.cpp:8:
> In member function 'void rxqt::run_loop::on_earlier_wakeup(int)'
> C:\workspace\ocube\ComponentStudio\rxqt\include\rxqt_run_loop.hpp:73: error: 'QCoreApplication' has not been declared
>              QCoreApplication::postEvent(this, new on_earlier_wakeup_event(this, msec));
>              ^~~~~~~~~~~~~~~~

And if I add `#include <QApplication>` to blueprintscene.cpp than problem is solved.
Is it normal?

Thank you for the your great library ;D

**Comment by tetsurom** [comment]
Hi @kehyoung 
Thank you for reporting, it is probably caused by lack of include.
I have added one include c80519a1d5bb4a39b0bf7e640cefb696f2212179 so could you please check it?

**Comment by kehyoung** [comment]
It works like a charm!
Thank you!! 😄
